apiVersion: batch/v1
kind: Job
metadata:
  name: optimizednnhyperparams
spec:
  template:
    spec:
      containers:
      - name: mytensorflow-sam 
        image: tensorflow/tensorflow:latest-gpu-py3
        imagePullPolicy: Always
        command:
          - "apt-get install wget"
          - "wget https://github.com/sam-may/ttH/blob/master/MVAs/nautilus/nautilus_exe.sh"
          - "source nautilus_exe.sh"
        resources:
          limits:
            memory: 48Gi
            cpu: "6"
            nvidia.com/gpu: "1"
          requests:
            memory: 4Gi
            cpu: "1"
            nvidia.com/gpu: "1"    
  backoffLimit: 5
