apiVersion: batch/v1
kind: Job
metadata:
  name: optimizednnhyperparams
  namespace: cms
  labels:
    k8s-app: mytensorflow-sam
spec:
  template:
    spec:
      containers:
      - name: optimizednnhyperparams
        image: tensorflow/tensorflow:latest-gpu-py3
        imagePullPolicy: Always
        command: 
            - sh
            - -c
            - "apt-get install wget && wget https://raw.githubusercontent.com/sam-may/ttH/master/MVAs/nautilus/nautilus_exe.sh && ls -althr && chmod 755 nautilus_exe.sh && ./nautilus_exe.sh" 
        resources:
          limits:
            memory: 48Gi
            cpu: "6"
            nvidia.com/gpu: "1"
          requests:
            memory: 4Gi
            cpu: "1"
            nvidia.com/gpu: "1" 
      restartPolicy: Never   
  backoffLimit: 0
